@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEzIiwiZW1haWwiOiIyMXhpZXBhdHJpY2VAZ21haWwuY29tIiwiaWF0IjoxNzY1NTAzODcwLCJleHAiOjE3NjU1OTAyNzB9.n8K3NywLnynnTPHvmJ_YsT9caYfR5z8kf1_ksnDs6A8

# AUTH
### GET /
GET http://localhost:8888

### Check email
POST http://localhost:8888/auth/checkEmail
Content-Type: application/json

{
    "email": "pvs@mail.com"
}

### Register
POST http://localhost:8888/auth/register
Content-Type: application/json

{
    "email": "pvs@mail.com",
    "password" : "12345678",
    "name" : "pattie",
    "type" : "manual"
}

### Login
POST http://localhost:8888/auth/login
Content-Type: application/json

{
    "email": "21xiepatrice@gmail.com",
    "password" : "12345678",
    "type" : "manual"
}

### Forgot Password
GET http://localhost:8888/auth/forgot-password
Content-Type: application/json

{
    "email": "21xiepatrice@gmail.com"
}


### Forgot Password
PUT http://localhost:8888/auth/reset-password
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEzIiwiZW1haWwiOiIyMXhpZXBhdHJpY2VAZ21haWwuY29tIiwiaWF0IjoxNzY1MjY2MzQ2LCJleHAiOjE3NjUyNjY5NDZ9.MPBeQjj0l7a91tPgmLs27jJrxMZkVXrfuUbL0PAa6zE",
    "newPassword" : "12345678"
}



# CATEGORIES
### Add Categories
POST http://localhost:8888/categories/add
Authorization: {{token}}
Content-Type: application/json

{
    "name" : "Category 6"
}


### Get Categories
GET http://localhost:8888/categories/getAll
Authorization: {{token}}


### Edit Categories
PUT http://localhost:8888/categories/update
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 8,
    "name" : "Category 3"
}

### Delete Categories
DELETE http://localhost:8888/categories/delete
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 12
}


# WALLETS
### Add Wallets
POST http://localhost:8888/wallets/add
Authorization: {{token}}
Content-Type: application/json

{
    "name" : "Wallet 1"
}


### Get Wallets
GET http://localhost:8888/wallets/getAll
Authorization: {{token}}


### Edit Wallets
PUT http://localhost:8888/wallets/update
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 2,
    "name" : "Wallet 3"
}

### Delete Wallets
DELETE http://localhost:8888/wallets/delete
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 2
}



# TARGETS
### Add Targets
POST http://localhost:8888/targets/add
Authorization: {{token}}
Content-Type: application/json

{
    "name" : "Target 3",
    "amount" : 300000045
}


### Get Targets
GET http://localhost:8888/targets/getAll
Authorization: {{token}}


### Edit Targets
PUT http://localhost:8888/targets/update
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 5,
    "name" : "Target 3",
    "amount" : 1550
}

### Delete Targets
DELETE http://localhost:8888/targets/delete
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 5
}


# Transaction

### Add
POST http://localhost:8888/transactions/add
Authorization: {{token}}
Content-Type: application/json

{
    "categoryId": 5,
    "walletId": 3,
    "amount": 2000,
    "spendType": "Income",
    "spendDate": "2030-10-04T00:00:00Z"
}

### Get All
GET http://localhost:8888/transactions/all
Authorization: {{token}}

### Get Specific
GET http://localhost:8888/transactions/1
Authorization: {{token}}

### Update
PUT http://localhost:8888/transactions/update
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 1,
    "categoryId": 6,
    "walletId": 3,
    "amount": 2000,
    "spendType": "Income",
    "spendDate": "2030-10-10T00:00:00Z"
}

### Delete 
DELETE http://localhost:8888/transactions/delete
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 1
}









