@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwIiwiZW1haWwiOiIyMXhpZXBhdHJpY2VAZ21haWwuY29tIiwiaWF0IjoxNzY5NjUxODc3LCJleHAiOjE3Njk3MzgyNzd9.w1FZpH3Av7OD5sRiMqtbW9mp1H6o2tJiCcnbqwrfYGk
@baseUrl = http://localhost:8888
@prodUrl = https://cash-track-by-pat.vercel.app/
@currUrl = {{baseUrl}}

# AUTH
### GET /
GET {{currUrl}}

### Check email
POST {{currUrl}}/auth/checkEmail
Content-Type: application/json

{
    "email": "pvs@mail.com"
}

### Register
POST {{currUrl}}/auth/register
Content-Type: application/json

{
    "email": "pvs@mail.com",
    "password" : "12345678",
    "name" : "pattie",
    "type" : "manual"
}

### Login
POST {{currUrl}}/auth/login
Content-Type: application/json

{
    "email": "pvs@mail.com",
    "password" : "12345678",
    "type" : "manual"
}

### Forgot Password
POST {{currUrl}}/auth/forgot-password
Content-Type: application/json

{
    "email": "21xiepatrice@gmail.com"
}


### Forgot Password
PUT {{currUrl}}/auth/reset-password
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEzIiwiZW1haWwiOiIyMXhpZXBhdHJpY2VAZ21haWwuY29tIiwiaWF0IjoxNzY1MjY2MzQ2LCJleHAiOjE3NjUyNjY5NDZ9.MPBeQjj0l7a91tPgmLs27jJrxMZkVXrfuUbL0PAa6zE",
    "newPassword" : "12345678"
}



# CATEGORIES
### Add Categories
POST {{currUrl}}/categories/add
Authorization: {{token}}
Content-Type: application/json

{
    "name" : "Category 6"
}


### Get Categories
GET {{currUrl}}/categories/getAll
Authorization: {{token}}


### Edit Categories
PUT {{currUrl}}/categories/update
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 8,
    "name" : "Category 3"
}

### Delete Categories
DELETE {{currUrl}}/categories/delete
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 12
}


# WALLETS
### Add Wallets
POST {{currUrl}}/wallets/add
Authorization: {{token}}
Content-Type: application/json

{
    "name" : "Wallet 1"
}


### Get Wallets
GET {{currUrl}}/wallets/getAll
Authorization: {{token}}


### Edit Wallets
PUT {{currUrl}}/wallets/update
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 2,
    "name" : "Wallet 3"
}

### Delete Wallets
DELETE {{currUrl}}/wallets/delete
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 2
}



# TARGETS
### Add Targets
POST {{currUrl}}/targets/add
Authorization: {{token}}
Content-Type: application/json

{
    "name" : "Target 3",
    "amount" : 300000045
}


### Get Targets
GET {{currUrl}}/targets/getAll
Authorization: {{token}}


### Edit Targets
PUT {{currUrl}}/targets/update
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 5,
    "name" : "Target 3",
    "amount" : 1550
}

### Delete Targets
DELETE {{currUrl}}/targets/delete
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 5
}


# Transaction

### Add
POST {{currUrl}}/transactions/add
Authorization: {{token}}
Content-Type: application/json

{
    "categoryId": 5,
    "walletId": 3,
    "amount": 2000,
    "spendType": "Income",
    "spendDate": "2030-10-04T00:00:00Z"
}

### Get All
GET {{currUrl}}/transactions/all
Authorization: {{token}}

### Get Specific
GET {{currUrl}}/transactions/1
Authorization: {{token}}

### Update
PUT {{currUrl}}/transactions/update
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 1,
    "categoryId": 6,
    "walletId": 3,
    "amount": 2000,
    "spendType": "Income",
    "spendDate": "2030-10-10T00:00:00Z"
}

### Delete 
DELETE {{currUrl}}/transactions/delete
Authorization: {{token}}
Content-Type: application/json

{
    "id" : 1
}









